### ISSUE TITLE
Adding a new sponsored listings in the admin panel isn't working

### ISSUE THREAD

**Issue by andrewb2** [Tradeversity/web-admin-panel#5]

**Comment by zachcb** [comment]
Fixed, need verification from @andrewb2.

**Comment by andrewb2** [comment]
I'm still not able to add a sponsored listing and have it show up in the admin panel or marketplace
